
/*ERRORS*/
export const GET_ERRORS = "GET_ERRORS";

/*COMMISSION*/
export const GET_COMMISSIONS = "GET_COMMISSIONS";
export const GET_COMMISSION = "GET_COMMISSION";
export const DELETE_COMMISSION = "DELETE_COMMISSION";
export const SEARCH_COMMISSIONS = "SEARCH_COMMISSIONS";

/*OPINION*/
export const GET_OPINIONS = "GET_OPINIONS";
export const GET_OPINION = "GET_OPINION";
export const DELETE_OPINION = "DELETE_OPINION";

/*USER*/
export const SET_CURRENT_USER = "SET_CURRENT_USER";

/*CUSTOMER*/
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_CUSTOMER = "GET_CUSTOMER";

/*SPECIALIST*/
export const GET_SPECIALISTS = "GET_SPECIALISTS";
export const GET_SPECIALIST = "GET_SPECIALIST";